apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: my-storage-pod
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["sh", "-c", "echo 'Hello from persistent storage!' > /mnt/data/hello.txt && sleep 3600"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /mnt/data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-pvc