name: Deploy DevOps Infra

on:
  push:
    branches: [main]

jobs:
  setup-devops-stack:
    name: Instala Herramientas Devops
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar repositorio
        uses: actions/checkout@v4

      - name:  Instalar herramientas DevOps
        run: bash instalar_herramientas_devops.sh
        
  Desplegar-Nginx:
    name: Desplegar Nginx
    runs-on: ubuntu-latest
    needs: setup-devops-stack

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        
      - name: Desplegar NGINX
        run: kubectl apply -f  nginx/nginx-deployment.yaml

      - name: Configurar Service NGINX
        run: kubectl apply -f  nginx/nginx-service.yaml
      
